# Generated by Django 5.0.1 on 2024-01-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_delete_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Признак публикации'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='blog_previews/', verbose_name='Превью (изображение)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='view_count',
            field=models.BigIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
